#!/bin/bash

JOB_NAME=hurricanehunter
RUN_DIR=/var/vcap/sys/run/$JOB_NAME
LOG_DIR=/var/vcap/sys/log/$JOB_NAME
CONFIG_DIR=/var/vcap/jobs/$JOB_NAME/config
EPHEMERAL=/var/vcap/data/$JOB_NAME
PERSISTENT=/var/vcap/store/$JOB_NAME
PIDFILE=$RUN_DIR/$JOB_NAME.pid
RUNAS=vcap

exec 1>> $LOG_DIR/$JOB_NAME.stdout.log
exec 2>> $LOG_DIR/$JOB_NAME.stderr.log

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR $EPHEMERAL
    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR $EPHEMERAL $PERSISTENT

    ## Start Code Here
    
    echo $$ >> $PIDFILE
    exec /var/vcap/packages/hurricanehunter/hurricanehunter \
         >>$LOG_DIR/loggregator.stdout.log \
         2>>$LOG_DIR/loggregator.stderr.log

    ;;

  stop)
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: hurricanehunter_ctl {start|stop}" ;;
esac
