---
name: dropsonde-warden
director_uuid: PLACEHOLDER-DIRECTOR-UUID

meta:
  stemcell:
    name: bosh-warden-boshlite-ubuntu

networks:
  - name: dropsonde
    subnets:
    - cloud_properties:
        name: random
      range: 10.244.3.0/24
      gateway: 10.244.3.1
      reserved:
      - 10.244.3.2 - 10.244.3.6
      - 10.244.3.11 - 10.244.3.11
      static:
      - 10.244.3.7 - 10.244.3.10

jobs:
  - name: dropsonde-test-harness
    instances: 1
    networks:
      - name: dropsonde
        static_ips:
        - 10.244.3.7

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

properties:
  warden:
    kernel_network_tuning_enabled: true
