---
name: (( merge ))

director_uuid: (( merge ))

releases:
  - name: dropsonde
    version: latest

networks: (( merge ))

jobs:
  - name: dropsonde-test-harness
    instances: (( merge ))
    resource_pool: (( merge ))
    templates:
    - name: dropsonde-agent
      release: dropsonde
    - name: hurricanehunter_0
      release: dropsonde
    - name: hurricanehunter_1
      release: dropsonde
    - name: hurricanehunter_2
      release: dropsonde
    networks:
     - name: dropsonde
       static_ips: (( merge ))
    properties:
       network_name: dropsonde

properties: (( merge ))

meta:
  stemcell:
    name: (( merge ))
    version: latest

compilation:
  workers: 1
  network: dropsonde
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

resource_pools: (( merge ))
update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

