---
name: (( merge ))

director_uuid: (( merge ))

releases:
  - name: hurricanehunter
    version: latest

networks: (( merge ))

jobs:
  - name: hurricanehunter
    template: hurricanehunter
    instances: 1
    resource_pool: small_z1
    networks:
      - name: dropsonde
        static_ips: (( merge ))
    properties:
      network_name: dropsonde

properties: (( merge ))

meta:
  stemcell:
    name: (( merge ))
    version: latest

compilation:
  workers: 1
  network: dropsonde
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

resource_pools:
  - name: small_z1
    network: dropsonde
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))
