#!/bin/bash

BOSH_RELEASES_DIR=${BOSH_RELEASES_DIR:-~/workspace}

RELEASE_HOME=$(dirname $0)/..
BOSH_STATUS=$(bosh status)
EXPECTED_DIRECTOR_NAME="Bosh Lite Director"
DIRECTOR_UUID=$(echo "$BOSH_STATUS" | grep UUID | awk '{print $2}')

if [[ "$(echo "$BOSH_STATUS" | grep Name)" != *"$EXPECTED_DIRECTOR_NAME"* ]]; then
  echo "Can only target $EXPECTED_DIRECTOR_NAME. Please use 'bosh target' before running this script."
  exit 1
fi

echo $DIRECTOR_UUID

$RELEASE_HOME/scripts/generate_deployment_manifest \
                                              warden \
                                              $* > $RELEASE_HOME/templates/manifest.yml

perl -pi -e "s/PLACEHOLDER-DIRECTOR-UUID/$DIRECTOR_UUID/g" $RELEASE_HOME/templates/manifest.yml

bosh deployment $RELEASE_HOME/templates/manifest.yml
bosh status
